site_name: wiki.aL1aL7.de
copyright: Copyright &copy; 2025 aL1aL7
repo_url: https://github.com/aL1aL7/wiki-al1al7
repo_name: aL1aL7/wiki-al1al7
theme:
    language: en
    font:
        text: "Quicksand"
    icon:
        repo: fontawesome/brands/git-alt
    name: material
    custom_dir: overrides
    logo: assets/images/logo-penguin-trans-300px.png
    favicon: assets/images/logo-penguin-trans-300px.png
    palette:
        scheme: slate
        primary: brown
        accent: green
    features:
        - content.code.copy
        - announce.dismiss
        - navigation.footer
        - navigation.instant
        - navigation.top
        - toc.integrate
        - navigation.tabs
        
plugins:
    - privacy
    - search
    - minify:
        minify_html: true
        htmlmin_opts:
            remove_comments: true
        cache_safe: true
markdown_extensions:
    - admonition
    - pymdownx.mark
    - pymdownx.highlight:
        use_pygments: true
        auto_title: false
        linenums: true
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: false
        linenums_style: table
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.details
    - pymdownx.superfences
    - def_list
    - attr_list
    - md_in_html
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.tasklist:
        custom_checkbox: true

nav:
    - Home: index.md
    - Downloads: downloads.md
    - Linux:
        - Mail Server: linux/mailserver.md
        - MariaDB: linux/mariadb.md
        - LXC Container: linux/lxc.md
        - Jekyll: linux/jekyll.md
        - nftables - Firewall: linux/nftables.md
        - Debian: linux/debian_install.md
        - mdadm - Software Raid: linux/mdadm.md
        - Python - Basics: linux/python.md
        - LUKS - Encryption: linux/luks.md
        - Caddy V2 Webserver: linux/caddy.md
        - fail2ban: linux/fail2ban.md
        - Docker @debian: linux/docker.md
        - LVM2 - Logical Volume Manager: linux/lvm2.md
        - iSCSI - Basics: linux/iscsi.md
        - Proxmox Backup Server - pbs: linux/pbs.md
    - Windows:
        - DISM - Basics: windows/dism.md
        - CLI - Snippets: windows/win_cli.md
    - About/Imprint: imprint.md

extra_css:
    - assets/stylesheets/extra.css
